---
- name: GlusterFS Host Connection to Cluster.
  hosts: localhost
  connection: local
  become: yes
  #become_method: sudo
  gather_facts: no

  vars:
    - gfshc_node_ip: 172.16.0.10
    - gfshc_mount_dir: /mnt/gluster
    - gluster_brick_name: os-glusterlab

  tasks:
  - name: Garantir que o glusterfs-client (e dependências) está instalado.
    apt:
      name: ['glusterfs-client','openssh-server','vim', 'wget','fuse']
      state: present
  
  - name: Adicionar o modulo FUSE ao Kernel.
    modprobe:
      name: fuse
      state: present

  - name: Verificar que o FUSE se encontra carregado.
    shell: "dmesg | grep -i fuse"
    register: "output"

  - debug: var=output.stdout_lines

  - name: Criar a pasta onde vai ser montado o volume.
    file:
      path: "{{ gfshc_mount_dir }}"
      mode: 0774
      owner: 's1lv4'
      group: 's1lv4'
      state: directory

  - name: Garantir que o volume se encontra montado.
    mount:
      name: "{{ gfshc_mount_dir }}"
      src: "{{ gfshc_node_ip }}:/{{ gluster_brick_name }}"
      fstype: glusterfs
      opts: "defaults,_netdev"
      state: mounted


